chart-dirs:
  - bitnami
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
debug: true
excluded-charts:
  - common
  - kubeapps
  - kibana
  - kong
  - mariadb-galera
  - ejbca
  - wavefront
  - dataplatform-bp1
  - dataplatform-bp2
remote: origin
